include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options and https://dart.dev/tools/linter-rules

linter:
  rules:
    always_declare_return_types: true
    cancel_subscriptions: true
    library_private_types_in_public_api: false
    noop_primitive_operations: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_pub_dependencies: true
    unawaited_futures: true
    unnecessary_to_list_in_spreads: true
    use_super_parameters: true
