name: rounded_loading_button
description: A simple implementation of an animated loading button widget for Flutter
version: 2.1.0
homepage: https://github.com/chrisedg87/flutter_rounded_loading_button

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter